// Code generated by prismic-ts-codegen. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Item in *About → we are*
 */
export interface AboutDocumentDataWeAreItem {
  /**
   * pic field in *About → we are*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about.we_are[].pic
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  pic: prismic.ImageField<never>;

  /**
   * title field in *About → we are*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: about.we_are[].title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * description field in *About → we are*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.we_are[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * Item in *About → event_titles*
 */
export interface AboutDocumentDataEventTitlesItem {
  /**
   * title field in *About → event_titles*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: about.event_titles[].title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;
}

/**
 * Item in *About → events*
 */
export interface AboutDocumentDataEventsItem {
  /**
   * pic field in *About → events*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about.events[].pic
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  pic: prismic.ImageField<never>;

  /**
   * title field in *About → events*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: about.events[].title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * description field in *About → events*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.events[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * Content for About documents
 */
interface AboutDocumentData {
  /**
   * about_pic_text field in *About*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.about_pic_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  about_pic_text: prismic.RichTextField;

  /**
   * about_pic field in *About*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about.about_pic
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  about_pic: prismic.ImageField<never>;

  /**
   * culture_description field in *About*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.culture_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  culture_description: prismic.RichTextField;

  /**
   * we are field in *About*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: about.we_are[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  we_are: prismic.GroupField<Simplify<AboutDocumentDataWeAreItem>>;

  /**
   * event_titles field in *About*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: about.event_titles[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  event_titles: prismic.GroupField<Simplify<AboutDocumentDataEventTitlesItem>>;

  /**
   * events field in *About*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: about.events[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  events: prismic.GroupField<Simplify<AboutDocumentDataEventsItem>>;

  /**
   * event_description field in *About*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.event_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  event_description: prismic.RichTextField;
}

/**
 * About document from Prismic
 *
 * - **API ID**: `about`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AboutDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<AboutDocumentData>, "about", Lang>;

/**
 * Item in *About-CDE → events*
 */
export interface AboutCdeDocumentDataEventsItem {
  /**
   * image field in *About-CDE → events*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about-cde.events[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * title field in *About-CDE → events*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Lorem
   * - **API ID Path**: about-cde.events[].title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * description field in *About-CDE → events*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Lorem ipsum dolor sit amet consectetur. Elementum nisl proin volutpat non purus.
   * - **API ID Path**: about-cde.events[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * Content for About-CDE documents
 */
interface AboutCdeDocumentData {
  /**
   * events field in *About-CDE*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: about-cde.events[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  events: prismic.GroupField<Simplify<AboutCdeDocumentDataEventsItem>>;
}

/**
 * About-CDE document from Prismic
 *
 * - **API ID**: `about-cde`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AboutCdeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<AboutCdeDocumentData>,
    "about-cde",
    Lang
  >;

/**
 * Item in *About-PDE → events*
 */
export interface AboutPdeDocumentDataEventsItem {
  /**
   * pde-title field in *About-PDE → events*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Lorem
   * - **API ID Path**: about-pde.events[].title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * image field in *About-PDE → events*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about-pde.events[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * description field in *About-PDE → events*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Lorem ipsum dolor sit amet consectetur. Elementum nisl proin volutpat non purus.
   * - **API ID Path**: about-pde.events[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * Content for About-PDE documents
 */
interface AboutPdeDocumentData {
  /**
   * events field in *About-PDE*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: about-pde.events[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  events: prismic.GroupField<Simplify<AboutPdeDocumentDataEventsItem>>;
}

/**
 * About-PDE document from Prismic
 *
 * - **API ID**: `about-pde`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AboutPdeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<AboutPdeDocumentData>,
    "about-pde",
    Lang
  >;

/**
 * Content for Apply documents
 */
interface ApplyDocumentData {
  /**
   * member_description field in *Apply*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: apply.member_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  member_description: prismic.RichTextField;

  /**
   * positions field in *Apply*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: apply.positions
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  positions: prismic.ContentRelationshipField<"position">;

  /**
   * application open field in *Apply*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: apply.application_open
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  application_open: prismic.DateField;

  /**
   * application close field in *Apply*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: apply.application_close
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  application_close: prismic.DateField;

  /**
   * interview start field in *Apply*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: apply.interview_start
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  interview_start: prismic.DateField;

  /**
   * interview end field in *Apply*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: apply.interview_end
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  interview_end: prismic.DateField;

  /**
   * application decision start field in *Apply*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: apply.application_decision_start
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  application_decision_start: prismic.DateField;

  /**
   * application decision end field in *Apply*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: apply.application_decision_end
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  application_decision_end: prismic.DateField;

  /**
   * partner reach out description field in *Apply*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: apply.partner_reach_out_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  partner_reach_out_description: prismic.RichTextField;
}

/**
 * Apply document from Prismic
 *
 * - **API ID**: `apply`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ApplyDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<ApplyDocumentData>, "apply", Lang>;

/**
 * Content for Case Study documents
 */
interface CaseStudyDocumentData {
  /**
   * Name field in *Case Study*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: case_study.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  name: prismic.TitleField;

  /**
   * description field in *Case Study*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: case_study.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * Case Study document from Prismic
 *
 * - **API ID**: `case_study`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CaseStudyDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<CaseStudyDocumentData>,
    "case_study",
    Lang
  >;

/**
 * Item in *CurrClient → currclient*
 */
export interface ClientDocumentDataCurrclientItem {
  /**
   * logo field in *CurrClient → currclient*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: client.currclient[].logo
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;

  /**
   * title field in *CurrClient → currclient*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: client.currclient[].title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * description field in *CurrClient → currclient*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: client.currclient[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * Content for CurrClient documents
 */
interface ClientDocumentData {
  /**
   * currclient field in *CurrClient*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: client.currclient[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  currclient: prismic.GroupField<Simplify<ClientDocumentDataCurrclientItem>>;
}

/**
 * CurrClient document from Prismic
 *
 * - **API ID**: `client`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ClientDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<ClientDocumentData>,
    "client",
    Lang
  >;

/**
 * Content for PartnerQuote documents
 */
interface ClientquoteDocumentData {
  /**
   * name field in *PartnerQuote*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: clientquote.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  name: prismic.TitleField;

  /**
   * title field in *PartnerQuote*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: clientquote.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * quote field in *PartnerQuote*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: clientquote.quote
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  quote: prismic.RichTextField;
}

/**
 * PartnerQuote document from Prismic
 *
 * - **API ID**: `clientquote`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ClientquoteDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<ClientquoteDocumentData>,
    "clientquote",
    Lang
  >;

/**
 * Item in *CurrClient → currclient*
 */
export interface CurrclientDocumentDataCurrclientItem {
  /**
   * logo field in *CurrClient → currclient*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: currclient.currclient[].logo
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;

  /**
   * title field in *CurrClient → currclient*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: currclient.currclient[].title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * description field in *CurrClient → currclient*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: currclient.currclient[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * caseStudyLink field in *CurrClient → currclient*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: currclient.currclient[].casestudylink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  casestudylink: prismic.LinkField;

  /**
   * case_study field in *CurrClient → currclient*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: currclient.currclient[].case
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  case: prismic.ContentRelationshipField<"case_study">;

  /**
   * websiteLink field in *CurrClient → currclient*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: currclient.currclient[].websitelink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  websitelink: prismic.LinkField;
}

/**
 * Content for CurrClient documents
 */
interface CurrclientDocumentData {
  /**
   * currclient field in *CurrClient*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: currclient.currclient[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  currclient: prismic.GroupField<
    Simplify<CurrclientDocumentDataCurrclientItem>
  >;
}

/**
 * CurrClient document from Prismic
 *
 * - **API ID**: `currclient`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type CurrclientDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<CurrclientDocumentData>,
    "currclient",
    Lang
  >;

/**
 * Content for team documents
 */
interface DDocumentData {
  /**
   * description field in *team*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: d.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * people field in *team*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: d.people
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  people: prismic.ContentRelationshipField<"people">;
}

/**
 * team document from Prismic
 *
 * - **API ID**: `d`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type DDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<DDocumentData>, "d", Lang>;

/**
 * Content for event documents
 */
interface EventDocumentData {
  /**
   * adssa field in *event*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: event.adssa
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  adssa: prismic.TitleField;
}

/**
 * event document from Prismic
 *
 * - **API ID**: `event`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type EventDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<EventDocumentData>, "event", Lang>;

/**
 * Item in *FAQ → question_answer*
 */
export interface FaqDocumentDataQuestionAnswerItem {
  /**
   * question field in *FAQ → question_answer*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.question_answer[].question
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  question: prismic.TitleField;

  /**
   * answer field in *FAQ → question_answer*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.question_answer[].answer
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  answer: prismic.RichTextField;

  /**
   * link_text field in *FAQ → question_answer*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.question_answer[].link_text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  link_text: prismic.RichTextField;

  /**
   * link field in *FAQ → question_answer*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.question_answer[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Content for FAQ documents
 */
interface FaqDocumentData {
  /**
   * question_answer field in *FAQ*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.question_answer[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  question_answer: prismic.GroupField<
    Simplify<FaqDocumentDataQuestionAnswerItem>
  >;
}

/**
 * FAQ document from Prismic
 *
 * - **API ID**: `faq`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FaqDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<FaqDocumentData>, "faq", Lang>;

/**
 * Item in *Home → top pictures*
 */
export interface HomeDocumentDataTopPicturesItem {
  /**
   * pic field in *Home → top pictures*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.top_pictures[].pic
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  pic: prismic.ImageField<never>;
}

/**
 * Item in *Home → we are section*
 */
export interface HomeDocumentDataWeAreSectionItem {
  /**
   * pic field in *Home → we are section*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.we_are_section[].pic
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  pic: prismic.ImageField<never>;

  /**
   * title field in *Home → we are section*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: home.we_are_section[].title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * description field in *Home → we are section*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.we_are_section[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * button text field in *Home → we are section*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.we_are_section[].button_text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  button_text: prismic.RichTextField;
}

/**
 * Item in *Home → reviews*
 */
export interface HomeDocumentDataReviewsItem {
  /**
   * description field in *Home → reviews*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.reviews[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * name field in *Home → reviews*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.reviews[].name
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  name: prismic.RichTextField;

  /**
   * role field in *Home → reviews*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.reviews[].role
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  role: prismic.RichTextField;
}

/**
 * Content for Home documents
 */
interface HomeDocumentData {
  /**
   * top pictures field in *Home*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: home.top_pictures[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  top_pictures: prismic.GroupField<Simplify<HomeDocumentDataTopPicturesItem>>;

  /**
   * we are section field in *Home*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: home.we_are_section[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  we_are_section: prismic.GroupField<
    Simplify<HomeDocumentDataWeAreSectionItem>
  >;

  /**
   * reviews field in *Home*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: home.reviews[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  reviews: prismic.GroupField<Simplify<HomeDocumentDataReviewsItem>>;

  /**
   * join team bottom pic field in *Home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.join_team_bottom_pic
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  join_team_bottom_pic: prismic.ImageField<never>;

  /**
   * join team people pic field in *Home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.join_team_people_pic
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  join_team_people_pic: prismic.ImageField<never>;

  /**
   * join team description field in *Home*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.join_team_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  join_team_description: prismic.RichTextField;

  /**
   * positions field in *Home*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: home.positions
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  positions: prismic.ContentRelationshipField<"position">;

  /**
   * join team button text field in *Home*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.join_team_button_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  join_team_button_text: prismic.RichTextField;
}

/**
 * Home document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<HomeDocumentData>, "home", Lang>;

/**
 * Item in *PastClient → pastclient*
 */
export interface PastclientDocumentDataPastclientItem {
  /**
   * Logo field in *PastClient → pastclient*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: pastclient.pastclient[].logo
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;

  /**
   * title field in *PastClient → pastclient*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: pastclient.pastclient[].title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * description field in *PastClient → pastclient*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: pastclient.pastclient[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * caseStudyLink field in *PastClient → pastclient*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: pastclient.pastclient[].casestudylink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  casestudylink: prismic.LinkField;

  /**
   * case_study field in *PastClient → pastclient*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: pastclient.pastclient[].case_study
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  case_study: prismic.ContentRelationshipField<"case_study">;

  /**
   * websiteLink field in *PastClient → pastclient*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: pastclient.pastclient[].websitelink
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  websitelink: prismic.LinkField;
}

/**
 * Content for PastClient documents
 */
interface PastclientDocumentData {
  /**
   * pastclient field in *PastClient*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: pastclient.pastclient[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  pastclient: prismic.GroupField<
    Simplify<PastclientDocumentDataPastclientItem>
  >;
}

/**
 * PastClient document from Prismic
 *
 * - **API ID**: `pastclient`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PastclientDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<PastclientDocumentData>,
    "pastclient",
    Lang
  >;

/**
 * Item in *People → people*
 */
export interface PeopleDocumentDataPeopleItem {
  /**
   * headshot field in *People → people*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: people.people[].headshot
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  headshot: prismic.ImageField<never>;

  /**
   * name field in *People → people*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: people.people[].name
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  name: prismic.TitleField;

  /**
   * pronouns field in *People → people*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: people.people[].pronouns
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  pronouns: prismic.RichTextField;

  /**
   * role field in *People → people*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: people.people[].role
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  role: prismic.RichTextField;

  /**
   * email field in *People → people*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: people.people[].email
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  email: prismic.RichTextField;

  /**
   * github field in *People → people*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: people.people[].github
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  github: prismic.LinkField;

  /**
   * linkedin field in *People → people*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: people.people[].linkedin
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  linkedin: prismic.LinkField;

  /**
   * website field in *People → people*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: people.people[].website
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  website: prismic.LinkField;

  /**
   * role_type field in *People → people*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: people.people[].role_type
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  role_type: prismic.SelectField<"lead" | "dev" | "designer">;
}

/**
 * Content for People documents
 */
interface PeopleDocumentData {
  /**
   * people field in *People*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: people.people[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  people: prismic.GroupField<Simplify<PeopleDocumentDataPeopleItem>>;
}

/**
 * People document from Prismic
 *
 * - **API ID**: `people`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PeopleDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<PeopleDocumentData>,
    "people",
    Lang
  >;

/**
 * Content for Person documents
 */
interface PersonDocumentData {
  /**
   * Headshot field in *Person*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: person.headshot
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  headshot: prismic.ImageField<never>;

  /**
   * Name field in *Person*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: person.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  name: prismic.TitleField;

  /**
   * role field in *Person*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: person.role
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  role: prismic.TitleField;

  /**
   * github field in *Person*
   *
   * - **Field Type**: Embed
   * - **Placeholder**: *None*
   * - **API ID Path**: person.github
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#embed
   */
  github: prismic.EmbedField;
}

/**
 * Person document from Prismic
 *
 * - **API ID**: `person`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PersonDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<PersonDocumentData>,
    "person",
    Lang
  >;

/**
 * Item in *Position → position*
 */
export interface PositionDocumentDataPositionItem {
  /**
   * name field in *Position → position*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: position.position[].name
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  name: prismic.TitleField;

  /**
   * short_description field in *Position → position*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: position.position[].short_description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  short_description: prismic.RichTextField;

  /**
   * tag_line field in *Position → position*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: position.position[].tag_line
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  tag_line: prismic.RichTextField;

  /**
   * work field in *Position → position*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: position.position[].work
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  work: prismic.RichTextField;

  /**
   * looking_for field in *Position → position*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: position.position[].looking_for
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  looking_for: prismic.RichTextField;

  /**
   * ideal_candidate field in *Position → position*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: position.position[].ideal_candidate
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  ideal_candidate: prismic.RichTextField;

  /**
   * application field in *Position → position*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: position.position[].application
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  application: prismic.LinkField;
}

/**
 * Content for Position documents
 */
interface PositionDocumentData {
  /**
   * position field in *Position*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: position.position[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  position: prismic.GroupField<Simplify<PositionDocumentDataPositionItem>>;
}

/**
 * Position document from Prismic
 *
 * - **API ID**: `position`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PositionDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<PositionDocumentData>,
    "position",
    Lang
  >;

interface ProDocumentData {}

/**
 * project document from Prismic
 *
 * - **API ID**: `pro`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<ProDocumentData>, "pro", Lang>;

/**
 * Item in *Project → Project*
 */
export interface ProjectDocumentDataProjectItem {
  /**
   * Logo Image field in *Project → Project*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: project.project[].logo_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo_image: prismic.ImageField<never>;

  /**
   * Website Image field in *Project → Project*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: project.project[].website_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  website_image: prismic.ImageField<never>;

  /**
   * Title field in *Project → Project*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Speak For The Trees
   * - **API ID Path**: project.project[].title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Subtitle field in *Project → Project*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Tree Stewardship Program
   * - **API ID Path**: project.project[].subtitle
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  subtitle: prismic.RichTextField;

  /**
   * Description field in *Project → Project*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Speak for the Trees Boston aims to improve the size and health of the urban forest in the greater Boston area, with a focus on under-served and under-canopied neighborhoods. They work with volunteers to inventory (collect data on) trees, plant trees, and educate those about trees...
   * - **API ID Path**: project.project[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Has Case Study field in *Project → Project*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: project.project[].has_case_study
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  has_case_study: prismic.BooleanField;

  /**
   * Case Problem field in *Project → Project*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project.project[].case_problem
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  case_problem: prismic.RichTextField;

  /**
   * Case Solution field in *Project → Project*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project.project[].case_solution
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  case_solution: prismic.RichTextField;

  /**
   * Live Website field in *Project → Project*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: project.project[].live_website
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  live_website: prismic.LinkField;
}

/**
 * Content for Project documents
 */
interface ProjectDocumentData {
  /**
   * Project field in *Project*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: project.project[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  project: prismic.GroupField<Simplify<ProjectDocumentDataProjectItem>>;
}

/**
 * Project document from Prismic
 *
 * - **API ID**: `project`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProjectDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<ProjectDocumentData>,
    "project",
    Lang
  >;

/**
 * Item in *Project2 → projects*
 */
export interface Project2DocumentDataProjectsItem {
  /**
   * logo field in *Project2 → projects*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: project2.projects[].logo
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;

  /**
   * title field in *Project2 → projects*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: project2.projects[].title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * subtitle field in *Project2 → projects*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project2.projects[].subtitle
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  subtitle: prismic.RichTextField;

  /**
   * description field in *Project2 → projects*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: project2.projects[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * case_study field in *Project2 → projects*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: project2.projects[].case_study
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  case_study: prismic.ContentRelationshipField<"case_study">;
}

/**
 * Content for Project2 documents
 */
interface Project2DocumentData {
  /**
   * projects field in *Project2*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: project2.projects[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  projects: prismic.GroupField<Simplify<Project2DocumentDataProjectsItem>>;
}

/**
 * Project2 document from Prismic
 *
 * - **API ID**: `project2`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type Project2Document<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<Project2DocumentData>,
    "project2",
    Lang
  >;

/**
 * Content for Team documents
 */
interface TeamDocumentData {
  /**
   * description field in *Team*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: team.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * people field in *Team*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: team.people
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  people: prismic.ContentRelationshipField<"people">;

  /**
   * case_study field in *Team*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: team.case_study
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  case_study: prismic.ContentRelationshipField<"case_study">;

  /**
   * team_name field in *Team*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: team.team_name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  team_name: prismic.KeyTextField;
}

/**
 * Team document from Prismic
 *
 * - **API ID**: `team`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type TeamDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<TeamDocumentData>, "team", Lang>;

export type AllDocumentTypes =
  | AboutDocument
  | AboutCdeDocument
  | AboutPdeDocument
  | ApplyDocument
  | CaseStudyDocument
  | ClientDocument
  | ClientquoteDocument
  | CurrclientDocument
  | DDocument
  | EventDocument
  | FaqDocument
  | HomeDocument
  | PastclientDocument
  | PeopleDocument
  | PersonDocument
  | PositionDocument
  | ProDocument
  | ProjectDocument
  | Project2Document
  | TeamDocument;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      AboutDocument,
      AboutDocumentData,
      AboutDocumentDataWeAreItem,
      AboutDocumentDataEventTitlesItem,
      AboutDocumentDataEventsItem,
      AboutCdeDocument,
      AboutCdeDocumentData,
      AboutCdeDocumentDataEventsItem,
      AboutPdeDocument,
      AboutPdeDocumentData,
      AboutPdeDocumentDataEventsItem,
      ApplyDocument,
      ApplyDocumentData,
      CaseStudyDocument,
      CaseStudyDocumentData,
      ClientDocument,
      ClientDocumentData,
      ClientDocumentDataCurrclientItem,
      ClientquoteDocument,
      ClientquoteDocumentData,
      CurrclientDocument,
      CurrclientDocumentData,
      CurrclientDocumentDataCurrclientItem,
      DDocument,
      DDocumentData,
      EventDocument,
      EventDocumentData,
      FaqDocument,
      FaqDocumentData,
      FaqDocumentDataQuestionAnswerItem,
      HomeDocument,
      HomeDocumentData,
      HomeDocumentDataTopPicturesItem,
      HomeDocumentDataWeAreSectionItem,
      HomeDocumentDataReviewsItem,
      PastclientDocument,
      PastclientDocumentData,
      PastclientDocumentDataPastclientItem,
      PeopleDocument,
      PeopleDocumentData,
      PeopleDocumentDataPeopleItem,
      PersonDocument,
      PersonDocumentData,
      PositionDocument,
      PositionDocumentData,
      PositionDocumentDataPositionItem,
      ProDocument,
      ProDocumentData,
      ProjectDocument,
      ProjectDocumentData,
      ProjectDocumentDataProjectItem,
      Project2Document,
      Project2DocumentData,
      Project2DocumentDataProjectsItem,
      TeamDocument,
      TeamDocumentData,
      AllDocumentTypes,
    };
  }
}
